kind: PersistentVolume
apiVersion: v1
metadata:
  name: dla-vol-local-01
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/dla-vol-01"
 