#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

export DLALAB_BIN="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DLAHOME/sbin/util/datalayer-env
$DLAHOME/sbin/util/datalayer-header "$@"
$DLAHOME/sbin/util/datalayer-env-echo

echo -e $BOLD$YELLOW"Datalayer Elasticsearch Help"$NOCOLOR$NOBOLD
echo
echo """
cd /opt
curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.tar.gz
tar -xvf elasticsearch-6.2.4.tar.gz
mv elasticsearch-6.2.4 elasticsearch
"""

echo -e $GREEN$BOLD"Elasticsearch API"$NOBOLD$NOCOLOR
echo
echo """
curl -X GET localhost:9200/_cat/health?v
curl -X GET localhost:9200/_cat/nodes?v
curl -X GET localhost:9200/_cat/indices?v
curl -X PUT localhost:9200/customer?pretty
curl -X GET localhost:9200/_cat/indices?v
curl -X PUT localhost:9200/customer/_doc/1?pretty -H 'Content-Type: application/json' -d'
{
  "name": "John Doe"
}
'
curl -X GET "localhost:9200/customer/_doc/1?pretty"
"""

echo
echo -e "Elasticsearch WEB Interface "$YELLOW"http://localhost:9100"$NOCOLOR" (Default username/password: xxx/xxx)"
echo """
git clone https://github.com/mobz/elasticsearch-head.git
cd elasticsearch-head
npm install
npm run start
open http://localhost:9100
"""
