#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

export DLALAB_BIN="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DLAHOME/sbin/datalayer-env

$DLAHOME/sbin/datalayer-header "$@"
$DLAHOME/sbin/datalayer-env-echo

echo -e $YELLOW$BOLD"Starting Datalayer Solr..."$NOBOLD$NOCOLOR
echo

cp $DLAHOME/conf/solr/solr.xml /var/datalayer/solr

cd $SOLR_HOME
# $SOLR_HOME/bin/solr start -cloud -noprompt -s $DLAHOME/conf/solr -p 7574 -z localhost:2181 -m 512m
# Instead of -c, you can use `-e cloud`, `-e schemaless` or `-e techproducts`.
# $SOLR_HOME/bin/solr start -e cloud -noprompt -p 8983 -z localhost:2181 -m 512m
# $SOLR_HOME/bin/solr start -e schemaless -noprompt -p 8983 -z localhost:2181 -m 512m
# $SOLR_HOME/bin/solr start -e techproducts -noprompt -p 8983 -z localhost:2181 -m 512m
$SOLR_HOME/bin/solr start -cloud -noprompt -s /var/datalayer/solr -p 8983 -m 1g -z localhost:2181

datalayer solr-help
