#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

source $DLAHOME/sbin/util/datalayer-cli-control

cd $SOLR_HOME

echo -e $BOLD$YELLOW"Datalayer Solr Help"$NOCOLOR$NOBOLD
echo
echo -e "Check Solr          "$YELLOW"$SOLR_HOME/bin/solr status"$NOCOLOR
echo
echo -e "View Solr           "$YELLOW"http://localhost:8983/solr"$NOCOLOR
echo -e "                    "$YELLOW"http://localhost:8983/solr/admin/info/system"$NOCOLOR
echo
echo -e "Create a collection "$YELLOW"$SOLR_HOME/bin/solr create -c demo -shards 2 -replicationFactor 2 -d $DLAHOME/conf/solr/conf"$NOCOLOR
echo -e "                    "$YELLOW"$SOLR_HOME/bin/solr create_collection -c demo -shards 2 -replicationFactor 2 -d $DLAHOME/conf/solr/conf"$NOCOLOR
echo
echo -e "Delete a collection "$YELLOW"$SOLR_HOME/bin/solr delete -c demo"$NOCOLOR
echo 
echo -e "Add documents       "$YELLOW"$SOLR_HOME/bin/post -c demo $SOLR_HOME/example/exampledocs/*.xml"$NOCOLOR
echo -e """
                    $SOLR_HOME/bin/post -c demo $SOLR_HOME/docs/
                    $SOLR_HOME/bin/post -c demo $SOLR_HOME/example/exampledocs/*.xml
                    $SOLR_HOME/bin/post -c demo $SOLR_HOME/example/exampledocs/books.json
                    $SOLR_HOME/bin/post -c demo $SOLR_HOME/example/exampledocs/books.csv

curl http://localhost:8983/solr/demo/update?commit=true -H 'Content-type:application/json' -d '
[
 {\"id\" : \"book1\",
  \"title\" : \"American Gods\",
  \"author\" : \"Neil Gaiman\"
 }
]'

                    $SOLR_HOME/bin/post -c demo -d \"<delete><id>SP2514N</id></delete>\"
"""
echo -e "Query documents     "$YELLOW"http://localhost:8983/solr/demo/select?q=video"$NOCOLOR
echo
echo -e "View shards         "$YELLOW"http://localhost:8983/solr/#/demo/collection-overview"$NOCOLOR
echo -e "                    "$YELLOW"http://localhost:8983/solr/#/demo_shard1_replica_n1"$NOCOLOR
echo
echo -e "View logs           "$YELLOW"tail -f $SOLR_HOME/server/logs/solr.log"$NOCOLOR
echo
echo -e """
Start preconfigured sets

$SOLR_HOME/bin/solr start -e cloud -noprompt
$SOLR_HOME/bin/solr start -e techproducts
"""
