#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

export DLABIN="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DLABIN/util/datalayer-env
$DLAHOME/sbin/datalayer-header "$@"
$DLABIN/util/datalayer-env-echo

echo -e $BOLD$YELLOW"Building Apache Spark WEB Site"$NOCOLOR$NOBOLD
echo

# You need to have [Ruby](https://www.ruby-lang.org/en/documentation/installation/) and
# [Python](https://docs.python.org/2/using/unix.html#getting-and-installing-the-latest-version-of-python)
# installed. Also install the following libraries:
# ```sh
#     $ sudo gem install jekyll jekyll-redirect-from pygments.rb
#     $ sudo pip install Pygments
#     # Following is needed only for generating API docs
#     $ sudo pip install sphinx pypandoc
#     $ sudo Rscript -e 'install.packages(c("knitr", "devtools", "roxygen2", "testthat", "rmarkdown"), repos="http://cran.stat.ucla.edu/")'
# ```
# (Note: If you are on a system with both Ruby 1.9 and Ruby 2.0 you may need to replace gem with gem2.0)

cd docs

SKIP_API=1 jekyll build

# You can modify the default Jekyll build as follows:

# Serve content locally on port 4000
# jekyll serve --watch

# Build the site with extra features used on the live page
# PRODUCTION=1 jekyll build

xdg-open _site/index.html
