#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

export DLABIN="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DLABIN/util/datalayer-env
$DLAHOME/sbin/datalayer-header "$@"
$DLABIN/util/datalayer-env-echo

echo -e $BOLD$YELLOW"Starting Datalayer Spark Shell..."$NOCOLOR$NOBOLD
echo

# export HADOOP_CONF_DIR=/sdk/conf/hadoop/

$SPARK_HOME/bin/spark-shell \
  --conf spark.sql.catalogImplementation=in-memory \
  --conf spark.sql.warehouse.dir=/tmp/spark-warehouse \
  --driver-memory 3g \
  --executor-memory 3g \
  "$@"
