#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $YELLOW$BOLD"Building Datalayer Spitfire K8S [$PWD]"$NOBOLD$NOCOLOR
echo

HADOOP_VERSION=2.9.0
SPARK_VERSION=2.2.0-k8s-0.5.0

DATALAYER_LAB_SHOW_HEADER=false

datalayer zeppelin-build \
  -Dspark.src.download.url=http://d3kbcqa49mib13.cloudfront.net/spark-2.2.0.tgz \
  -Dspark.bin.download.url=file:///$DLAHOME/packages/spark-2.2.0-k8s-0.5.0.tar.gz \
  "$@"
