#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

export DLALAB_BIN="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DLAHOME/sbin/util/datalayer-env

$DLAHOME/sbin/util/datalayer-header "$@"
$DLAHOME/sbin/util/datalayer-env-echo

echo -e $RED$BOLD"Existing Zookeeper data will be lost forever!!!"$NOBOLD$NOCOLOR
echo
#read -p "Are you sure you want to remove all Zookeeper persisted files, they will be lost forever!!! (y/N)?" -n 1 -r
echo -e $YELLOW"Are you sure you want to remove $BOLD'/var/datalayer/zookeeper'$NOBOLD (y/N)?"$NOCOLOR
read REPLY

if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo
    echo "Removing Zookeeper '/var/datalayer/zookeeper'..."
    rm -fr /var/datalayer/zookeeper
    echo "Zookeeper files are now removed."
else
  echo
  echo "I didn't touch any file... Come back when you want..."
fi

echo
