#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# #############################################################################

# [0m  reset; clears all colors and styles (to white on black)

# [1m  bold on
# [3m  italics on
# [4m  underline on
# [7m  inverse on; reverses foreground & background colors
# [9m  strikethrough on

# [22m bold off
# [23m italics off
# [24m # [27m inverse off
# [29m strikethrough off

# [30m set foreground color to black
# [31m set foreground color to red
# [32m set foreground color to green
# [33m set foreground color to yellow
# [34m set foreground color to blue
# [35m set foreground color to magenta (purple)
# [36m set foreground color to cyan
# [37m set foreground color to white
# [38m set foreground color to ???
# [39m set foreground color to default (white)

# [40m set background color to black
# [41m set background color to red
# [42m set background color to green
# [43m set background color to yellow
# [44m set background color to blue
# [45m set background color to magenta (purple)
# [46m set background color to cyan
# [47m set background color to white
# [48m set background color to ???
# [49m set background color to default (black)

# #############################################################################

# noir='\e[0;30m'
# gris='\e[1;30m'
# rougefonce='\e[0;31m'
# rose='\e[1;31m'
# vertfonce='\e[0;32m'
# vertclair='\e[1;32m'
# orange='\e[0;33m'
# jaune='\e[1;33m'
# bleufonce='\e[0;34m'
# bleuclair='\e[1;34m'
# violetfonce='\e[0;35m'
# violetclair='\e[1;35m'
# cyanfonce='\e[0;36m'
# cyanclair='\e[1;36m'
# grisclair='\e[0;37m'
# blanc='\e[1;37m'

# #############################################################################

export NOCOLOR='\x1b[0m'

export DEFAULT_COLOR='\x1b[0m'

export OK='\x1b[32m'
export GREEN='\x1b[32m'
export GREEN_BCK='\x1b[42m'

export FAINT='\x1b[2m'

export WARN='\x1b[33m'
export YELLOW='\x1b[33m'
export YELLOW_BCK='\x1b[43m'

export ERR='\x1b[31m'
export RED='\x1b[31m'
export RED_BCK='\x1b[41m'

export BLUE='\x1b[34m'
export BLUE_BCK='\x1b[44m'

export ORANGE='\x0b[33m'

export WHITE_BCK='\x1b[7m'
# export WHITE_BCK='\x1b[47m\x1b[40m'

# #############################################################################

export MESSAGE_OK=$OK'[OK]'$NOCOLOR
export MESSAGE_ERR=$ERR'[ERROR]'$NOCOLOR
export MESSAGE_WARN=$WARN'[WARN]'$NOCOLOR

# #############################################################################

export BOLD='\x1b[1m'
export NOBOLD='\x1b[22m'

# #############################################################################

export CURSOR_UP='\e[1A'

# #############################################################################
