#!/usr/bin/env bash

# Licensed to Datalayer (http://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

(xscreensaver -nosplash &) &>/dev/null
# xscreensaver -nosplash & > /dev/null

export PATH=$PATH:.

export DLA_SRC=/src
export DLA_REPOSITORY=$HOME/.m2/repository
# export DLA_HADOOP=local
# export DLA_HADOOP_STATUS=started

export JAVA_HOME=/opt/jdk
export PATH=$JAVA_HOME/bin:$PATH
unset JAVA_TOOL_OPTIONS

# export DOCKER_API_VERSION=1.24
export DOCKER_API_VERSION=1.25

export KUBERNETES_HOME=/opt/kubernetes
export PATH=$KUBERNETES_HOME/client/bin:$KUBERNETES_HOME/server/kubernetes/server/bin:$PATH
export KUBERNETES_PROVIDER=none
export NUM_NODES=2
export KUBERNETES_NUM_NODES=2
export KUBECONFIG=~/.kube/config

export HELM_HOME=/opt/helm
export PATH=$HELM_HOME:$PATH

# export PATH=$HOME/miniconda/bin:$PATH

export GRE_HOME=/opt/mozilla-1.9.1/mozilla-1-9-1-920bcf17a9e1/obj-xulrunner/dist/bin
export PATH=$GRE_HOME:$PATH

export FORREST_HOME=/opt/forrest-0.9
export PATH=$FORREST_HOME/bin:$PATH

export R_HOME=/usr/lib/R
export PATH=$R_HOME/bin:$PATH

export ECLIPSE_HOME=/opt/eclipse
export PATH=$ECLIPSE_HOME/bin:$PATH

export GO_HOME=/opt/go
export GOROOT=$GO_HOME
export PATH=$GOROOT/bin:$PATH
export GOPATH=/src/go
export PATH=$GOPATH/bin:$PATH

export GEPHI_HOME=/opt/gephi-0.9.1
export PATH=$GEPHI_HOME/bin:$PATH

# export H20_HOME=/opt/h2o

export DYLD_LIBRARY_PATH=/usr/lib

export LUKE_HOME=/opt/luke-6.1.0
export PATH=$LUKE_HOME/bin:$PATH

export GROOVY_HOME=/opt/groovy-2.2.1
export PATH=$PATH:$GROOVY_HOME/bin

export GRAILS_HOME=/opt/grails-2.2.0
export PATH=$PATH:$GRAILS_HOME/bin

# export CLOJURE_HOME=/opt/clojure-1.6.0
# export CLASSPATH=$CLOJURE_HOME/clojure-1.6.0.jar:$CLASSPATH

# export LEININGEN_HOME=/opt/leiningen-2.3.4
# export PATH=$LEININGEN_HOME/bin:$PATH

export SCALA_HOME=/opt/scala-2.11.8
export PATH=$SCALA_HOME/bin:$PATH

export SBT_HOME=/opt/sbt-0.13.2
export PATH=$SBT_HOME/bin:$PATH

export ANT_HOME=/opt/apache-ant-1.9.6
export PATH=$ANT_HOME/bin:$PATH

# export IVY_HOME=/opt/apache-ivy-2.4.0
# export CLASSPATH=$IVY_HOME/ivy-2.3.0-rc1.jar:$CLASSPATH

export MAVEN_HOME=/opt/apache-maven-3.3.9
export PATH=$MAVEN_HOME/bin:$PATH
export MAVEN_OPTS="-Xmx8g -Xms2g -XX:ReservedCodeCacheSize=2g"

export GRADLE_HOME=/opt/gradle-3.3
export PATH=$GRADLE_HOME/bin:$PATH

export ANDROID_HOME=/opt/android-sdk-linux
export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
export ANDROID_STUDIO_HOME=/opt/android-studio
export PATH=$ANDROID_STUDIO_HOME/bin:$PATH

# export AZURE_CLI_HOME=/opt/azure-cli.0.9.2
# export PATH=$AZURE_CLI_HOME/bin:$PATH

export JYTHON_HOME=/opt/jython2.2.1
export PATH=$JYTHON_HOME:$PATH

export GIT_LFS_HOME=/opt/git-lfs-1.5.2
export PATH=$GIT_LFS_HOME:$PATH

# export DATAIKU_HOME=/opt/dataiku
# export PATH=$DATAIKU_HOME/bin:$PATH

# export MONGODB_HOME=/opt/mongodb
# export PATH=$MONGODB_HOME/bin:$PATH

# export ELASTICSEARCH_HOME=/opt/elasticsearch-1.7.0
# export PATH=$ELASTICSEARCH_HOME/bin:$PATH

# export ZOOKEEPER_HOME=/opt/zookeeper-3.5.0
# export ZOOKEEPER_CONF_DIR=/etc/zookeeper/conf
# export ZOOKEEPER_CONF_FILE=/sdk/conf-template/zookeeper/zoo.cfg
# export ZOO_LOG_DIR=$ZOOKEEPER_HOME/logs
# export PATH=$ZOOKEEPER_HOME/bin:$PATH

# export HADOOP_HOME=/sdk/ext/hadoop-2.7.1
# export PATH=$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$PATH
# export HADOOP_CONF_DIR=$DLA_HOME/conf/hadoop
# export HADOOP_CONF_DIR=/etc/hadoop/conf
# export HADOOP_CONF_DIR=/sdk/ext/hadoop-3.0.0-alpha1/etc/hadoop datalayer hadoop
# export HADOOP_CLASSPATH=/opt/hadoop-lzo/build/hadoop-lzo-0.4.17-SNAPSHOT.jar:$HADOOP_CLASSPATH
# export JAVA_LIBRARY_PATH=/usr/local/lzo-2.06/lib:/o/hadoop-lzo/build/native/???linux???/lib:$JAVA_LIBRARY_PATH

# export HBASE_HOME=/opt/hbase-1.2.0
# export PATH=$HBASE_HOME/bin:$PATH
# export HBASE_CONF_DIR=/etc/hbase/conf

# export PIG_HOME=/opt/pig-0.12.0
# export PATH=$PIG_HOME/bin:$PATH

# export HIVE_HOME=/opt/hive-0.7.1
# export PATH=$HIVE_HOME/bin:$PATH

# export CASSANDRA_HOME=/opt/apache-cassandra-2.0.5
# export PATH=$CASSANDRA_HOME/bin:$PATH

export GATE_HOME=/opt/src/gate
export PATH=$GATE_HOME/bin:$PATH

# export OPENNLP_HOME=/opt/apache-opennlp-1.5.3
# export PATH=$OPENNLP_HOME/bin:$PATH

# export MAHOUT_HOME=/s/mahout
# export PATH=$MAHOUT_HOME/bin:$PATH

# export KAFKA_HOME=/opt/kafka-0.7.2-incubating-src
# export PATH=$KAFKA_HOME/bin:$PATH

# export AKKA_HOME=/opt/akka-2.3.3
# export PATH=$AKKA_HOME/bin:$PATH

# export SPARK_HOME=/opt/spark-2.0.0
# export PATH=$SPARK_HOME/bin:$PATH
# export SPARK_DAEMON_MEMORY=1g
# export SPARK_JAVA_OPTS="-Xms512m -Xmx2g -Dspark.executor.memory=512m -Dspark.yarn.executor.memoryOverhead=100 -Dspark.executor.memory=256m"

export PYTHONIOENCODING="UTF-8"

export RESTER_HOME=/opt/rester
export PATH=$RESTER_HOME/bin:$PATH

export PATH=$PATH:/usr/local/pkg-config-0.23/bin
export PATH=/opt/local/bin:/opt/local/sbin:$PATH

# source $DLA_HOME/bin/datalayer git-completion 

DATALAYER_SHOW_HEADER=false datalayer zinc-start

alias c='datalayer cls'
alias cls='datalayer cls'
alias ll='ls -alp'

alias w='cd /w; ll'

alias t='datalayer'
alias k='kubectl'
alias d='cd /d; cls; datalayer todo /d; datalayer repos-echo'
alias td='datalayer todo'

alias protoc-2.4.1='datalayer protoc-2.4.1'
alias protoc-2.5.0='datalayer protoc-2.5.0'

alias clj='datalayer clj'
alias clojure='datalayer clj'
alias sbt='datalayer sbt'

# datalayer mouse-fix

# 2880 2600 2400 2200 2000 1800
# datalayer screen-resolution 1600 

# rm ~/hs_err_pid* > /dev/null
# rm ~/ajcore.*.txt > /dev/null

# d
