apiVersion: v1
kind: Pod
metadata:
  name: dla-dns-test-2
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  nodeSelector:
    kubernetes.io/hostname: ip-10-0-0-77
  restartPolicy: Never
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
